Labels{1}='Number of filaments in the structure';
Labels{2}='Volume fraction of filaments';
Labels{3}='Cross-sectional area';
Labels{4}='Cross-sectional density';
Labels{5}='Cross-sectional volume fraction';
Labels{6}='Cross-sectional number of filaments';
Labels{7}='Height';
Labels{8}='Anisotropy of filaments'; 
Labels{9}='Length of filaments'; 
Labels{10}='Angle of filaments'; 
Labels{11}='Bendiness of filaments'; 
Labels{12}='Bending energy density of filaments'; 
Labels{13}='Base/tip ratio of cross-sectional density';
Labels{14}='Base/tip ratio of structure height';
Labels{15}='Base/tip ratio of filament length';
Labels{16}='Base/tip ratio of filament angle';
Labels{17}='Base/tip ratio of filament bendiness';
Labels{18}='Base/tip ratio of bending energy density';

